### ISSUE TITLE
npm has been fixed - time to deprecate

### ISSUE THREAD

**Issue by bebraw** [cdaringe/lerna-npm-readme-hack#3]
Hi,

See https://github.com/npm/registry/issues/42#issuecomment-274175490 . Looks like the hack can be deprecated. 👍

**Comment by cdaringe** [comment]
Yaaaahoooo. Will update the package and readme later

**Comment by cdaringe** [comment]
`npm deprecate ...` has been executed against `1.0.6`

**Comment by cdaringe** [comment]
thx, btw!
